#!/usr/bin/env bash
# displaye numbers from 1 to 100
# prints FizzBuzz as a result of multiples of numbers
for i in {1..100}
do
    if [ $((i % 5)) -eq 0 -a $((i % 3)) -eq 0 ]
    then
	echo "FizzBuzz"
    elif [ $((i % 5)) -eq 0 ]
    then
	echo "Buzz"
    elif [ $((i % 3)) -eq 0 ]
    then
	echo "Fizz"
    else
	echo "$i"
    fi
done
